name: Github Action dotnet webapp

on:
  schedule:
    - cron: '* 1 * * *' # every Friday 06:30 UTC
    
  push:
    branches: [ "main" ]
jobs:

  job-test:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "teste"

  #marketplace
  build:
    name: .Net Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore **/*.csproj
    - name: Build
      run: dotnet build **/*.csproj --no-restore
          
