name: Github Action dotnet webapp

on:
  push:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
schedule:
- cron: ‘* 1 * * *’ # every Friday 06:30 UTC